image: gcc4.8

env:
  - PREFIX=/opt/obsrvbl/ossec
  - TARGET=local
  - VERSION=2.8.2

script:
  - sudo apt-get update
  - sudo apt-get install ubuntu-dev-tools build-essential debhelper
  - tar czf ossec-hids-$TARGET_$VERSION.orig.tar.gz ossec-hids/
  - make copy
  - ( cd ossec-hids-$TARGET-$VERSION/ ; dch -D precise -i "Based on ossec-hids@$DRONE_COMMIT" )
  - make deb

notify:
  email:
    recipients:
      - engineering@obsrvbl.com

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: onstatic
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: debs/
    target: ossec-hids/$DRONE_BRANCH/
    recursive: true
    when:
      owner: obsrvbl
