image: python2.7

env:
  - PREFIX=/opt/obsrvbl/ossec
  - TARGET=local
  - VERSION=2.8.2

script:
  - gem install fpm
  - rbenv rehash
  - make deb

notify:
  email:
    recipients:
      - engineering@obsrvbl.com

publish:
  s3:
    acl: public-read
    region: us-east-1
    bucket: onstatic
    access_key: $$AWS_KEY
    secret_key: $$AWS_SECRET
    source: debs/
    target: ossec-hids/$DRONE_BRANCH/
    recursive: true
    when:
      owner: obsrvbl
